development:
  adapter: sqlite3
  database: db/ddp_development

rdw_development:
  adapter: oracle_enhanced
  host: bmic-odb.mdc.musc.edu
  username: RDCP_DDP
  password: winter2020
  database: rdmprd
